#! /bin/sh
set -x
mkdir -p auto
mkdir -p po

libtoolize --automake
gettextize --force --no-changelog
cp /usr/share/gettext/gettext.h .
aclocal -I m4

autoheader
automake --foreign --add-missing
autoconf
