MudlibDir	    m3_mudlib
IncludeDir      /:/include
GlobalInclude   <config.h>
SimulEfunFile   /simul_efun.lpc
MasterFile	    /master.lpc
#Port		    4000:telnet
LogWithDate	    Yes

# Optional settings
SaveBinaryDir    /bin
