{
  "__PACKAGE_UIDS__", " ",
  "__CALLOUT_HANDLES__", " ",
  "__SAVE_EXTENSION__", " \".o\"",
  "__DEFAULT_PRAGMAS__", " PRAGMA_WARNINGS + PRAGMA_STRICT_TYPES",
  "__CONFIG_FILE_DIR__", " \"/usr/local/etc\"",
  "__HEARTBEAT_INTERVAL__", " 2000000",
  "__COMPRESS_FUNCTION_TABLES__", " ",
  "__NO_LIGHT__", " ",
  "__SYSMALLOC__", " ",
  "__RESTRICTED_ED__", " ",
  "__ARRAY_STATS__", " ",
  "__AUTO_TRUST_BACKBONE__", " ",
  "__SMALL_STRING_SIZE__", "     100",
  "__HEART_BEAT_CHUNK__", "      32",
  "__PACKAGE_CONTRIB__", " ",
  "__RECEIVE_SNOOP__", " ",
  "__OLD_ED__", " ",
  "__OLD_RANGE_BEHAVIOR__", " ",
  "__CACHE_STATS__", " ",
  "__LARGE_STRING_SIZE__", "     1000",
  "__APPLY_CACHE_BITS__", " 11",
  "__BINARIES__", " ",
  "__STRING_STATS__", " ",
  "__NO_ANSI__", " ",
  "__SANE_EXPLODE_STRING__", " ",
  "__LOG_CATCHES__", " ",
  "__MAX_SAVE_SVALUE_DEPTH__", " 25",
  "__CALLOUT_CYCLE_SIZE__", " 32",
  "__PACKAGE_SOCKETS__", " ",
  "__THIS_PLAYER_IN_CALL_OUT__", " ",
  "___OPTIONS_H___", " ",
  "__MESSAGE_BUFFER_SIZE__", " 4096",
  "__REVERSIBLE_EXPLODE_STRING__", " ",
  "__STRIP_BEFORE_PROCESS_INPUT__", " ",
  "__NO_SHADOWS__", " ",
  "__NEXT_MALLOC_DEBUG__", " ",
  "__TRAP_CRASHES__", " ",
  "__LARGEST_PRINTABLE_STRING__", " 8192",
  "__CUSTOM_CRYPT__", " ",
  "__PACKAGE_DEVELOP__", " ",
  "__COMMAND_BUF_SIZE__", "      2000",
  "__PACKAGE_MATH__", " ",
};

#define NUM_OPTION_DEFS 42

