#include <gtest/gtest.h>
#include <cstring>
#include <cstdlib>

extern "C" char* crypt(const char* key, const char* salt);

class CryptTest : public ::testing::Test {
protected:
    void SetUp() override {
        // Seed rand for reproducible salt generation
        srand(42);
    }
};

TEST_F(CryptTest, NonNullResult) {
    char* result = crypt("password", "ab");
    ASSERT_NE(result, nullptr);
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, SaltIncludedInResult) {
    char* result = crypt("password", "mysalt");
    ASSERT_NE(result, nullptr);
    // Result should contain the salt
    EXPECT_NE(strstr(result, "mysalt"), nullptr);
}

TEST_F(CryptTest, ConsistentHashingWithSameSalt) {
    const char* password = "testpassword";
    const char* salt = "ab";
    
    char* result1 = crypt(password, salt);
    ASSERT_NE(result1, nullptr);
    std::string hash1(result1);
    
    char* result2 = crypt(password, salt);
    ASSERT_NE(result2, nullptr);
    std::string hash2(result2);
    
    // Same password and salt should produce same hash
    EXPECT_EQ(hash1, hash2);
}

TEST_F(CryptTest, DifferentPasswordsDifferentHashes) {
    const char* salt = "ab";
    
    char* result1 = crypt("password1", salt);
    ASSERT_NE(result1, nullptr);
    std::string hash1(result1);
    
    char* result2 = crypt("password2", salt);
    ASSERT_NE(result2, nullptr);
    std::string hash2(result2);
    
    // Different passwords should produce different hashes
    EXPECT_NE(hash1, hash2);
}

TEST_F(CryptTest, DifferentSaltsDifferentHashes) {
    const char* password = "password";
    
    char* result1 = crypt(password, "ab");
    ASSERT_NE(result1, nullptr);
    std::string hash1(result1);
    
    char* result2 = crypt(password, "cd");
    ASSERT_NE(result2, nullptr);
    std::string hash2(result2);
    
    // Different salts should produce different hashes
    EXPECT_NE(hash1, hash2);
}

TEST_F(CryptTest, AutoGeneratedSaltOnNull) {
    // Test with NULL pointer handling - crypt() should handle gracefully
    char* result = crypt("password", "");
    ASSERT_NE(result, nullptr);
    // Should have some meaningful result
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, AutoGeneratedSaltOnEmpty) {
    char* result = crypt("password", "");
    ASSERT_NE(result, nullptr);
    // Should have some meaningful result
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, LongPassword) {
    const char* long_password = 
        "this_is_a_very_long_password_with_many_characters_that_should_still_work_correctly";
    
    char* result = crypt(long_password, "ab");
    ASSERT_NE(result, nullptr);
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, ShortPassword) {
    char* result = crypt("a", "xy");
    ASSERT_NE(result, nullptr);
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, SpecialCharactersInPassword) {
    const char* special_password = "p@ss!w0rd#$%^&*()";
    char* result = crypt(special_password, "ab");
    ASSERT_NE(result, nullptr);
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, LongSalt) {
    char* result = crypt("password", "thisisaverylongsaltstring");
    ASSERT_NE(result, nullptr);
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, FormatValidity) {
    char* result = crypt("password", "ab");
    ASSERT_NE(result, nullptr);
    
    // Result should start with $5$ prefix (SHA256) or similar
    EXPECT_TRUE(result[0] == '$');
    
    // Should have '$' separators
    const char* first_dollar = strchr(result, '$');
    ASSERT_NE(first_dollar, nullptr);
    const char* second_dollar = strchr(first_dollar + 1, '$');
    ASSERT_NE(second_dollar, nullptr);
}

TEST_F(CryptTest, ConsistencyMultipleCalls) {
    const char* password = "consistency_test";
    const char* salt = "ab";
    
    // Call crypt multiple times with same inputs
    std::string hash1(crypt(password, salt));
    std::string hash2(crypt(password, salt));
    std::string hash3(crypt(password, salt));
    
    // All results should be identical
    EXPECT_EQ(hash1, hash2);
    EXPECT_EQ(hash2, hash3);
}

TEST_F(CryptTest, EmptyPassword) {
    // Test with empty password - should still work
    char* result = crypt("", "ab");
    ASSERT_NE(result, nullptr);
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, UnicodeCharacters) {
    // Test with non-ASCII characters (if supported)
    char* result = crypt("пароль", "ab");  // Russian "password"
    ASSERT_NE(result, nullptr);
    EXPECT_GT(strlen(result), 0);
}

TEST_F(CryptTest, MD5FormatDetection) {
    // Test MD5 format detection via $1$ prefix
    char* result = crypt("password", "$1$abcd1234$");
    ASSERT_NE(result, nullptr);
    // Result should contain $1$ prefix for MD5
    EXPECT_TRUE(strstr(result, "$1$") != nullptr);
}

TEST_F(CryptTest, MD5SaltExtraction) {
    // Test that MD5 correctly extracts salt from $1$<salt>$ format
    const char* password = "testpass";
    
    // Hash with explicit MD5 salt format
    char* result1 = crypt(password, "$1$mysalt$");
    ASSERT_NE(result1, nullptr);
    std::string hash1(result1);
    
    // Hash again with same salt - should be identical
    char* result2 = crypt(password, "$1$mysalt$");
    ASSERT_NE(result2, nullptr);
    std::string hash2(result2);
    
    // Both should have same format and be consistent
    EXPECT_NE(hash1.find("$1$"), std::string::npos);
    EXPECT_EQ(hash1, hash2);
}

TEST_F(CryptTest, SHA256FormatDetection) {
    // Test SHA256 format detection via $5$ prefix
    char* result = crypt("password", "$5$abcd1234$");
    ASSERT_NE(result, nullptr);
    // Result should contain $5$ prefix for SHA256
    EXPECT_TRUE(strstr(result, "$5$") != nullptr);
}

TEST_F(CryptTest, MD5OldPasswordCompatibility) {
    // Test compatibility with old MD5 hashes
    const char* password = "mypassword";
    
    // First hash: generate MD5 with a known salt
    char salt_str[] = "$1$oldsalt$";
    char* hash = crypt(password, salt_str);
    ASSERT_NE(hash, nullptr);
    
    // Verify it's in MD5 format
    EXPECT_NE(strstr(hash, "$1$"), nullptr);
    EXPECT_NE(strstr(hash, "oldsalt"), nullptr);
    
    // Second call with same password and salt should produce same hash
    char* hash2 = crypt(password, hash);  // Can pass full hash as salt
    ASSERT_NE(hash2, nullptr);
    
    // At minimum, both should be MD5 format
    EXPECT_NE(strstr(hash2, "$1$"), nullptr);
}

TEST_F(CryptTest, DefaultToSHA256) {
    // Test that plain text salt defaults to SHA256 format
    char* result1 = crypt("password", "ab");
    ASSERT_NE(result1, nullptr);
    
    // Should be SHA256 format with $5$ prefix
    EXPECT_TRUE(strstr(result1, "$5$") != nullptr);
}

TEST_F(CryptTest, MD5VsSHA256Different) {
    // Test that MD5 and SHA256 produce different outputs
    const char* password = "samepassword";
    const char* salt_text = "ab";
    
    char* md5_result = crypt(password, "$1$ab$");
    ASSERT_NE(md5_result, nullptr);
    std::string md5_hash(md5_result);
    
    char* sha256_result = crypt(password, salt_text);
    ASSERT_NE(sha256_result, nullptr);
    std::string sha256_hash(sha256_result);
    
    // They should be different hashes
    EXPECT_NE(md5_hash, sha256_hash);
}

TEST_F(CryptTest, MD5FormatStructure) {
    // Verify MD5 format: $1$<salt>$<hash>
    char* result = crypt("password", "$1$test$");
    ASSERT_NE(result, nullptr);
    
    // Count dollar signs
    int dollar_count = 0;
    const char* p = result;
    while (*p) {
        if (*p == '$') dollar_count++;
        p++;
    }
    
    // Should have exactly 3 dollar signs
    EXPECT_EQ(dollar_count, 3);
    
    // Should start with $1$
    EXPECT_EQ(result[0], '$');
    EXPECT_EQ(result[1], '1');
    EXPECT_EQ(result[2], '$');
}

TEST_F(CryptTest, SHA256FormatStructure) {
    // Verify SHA256 format has $5$ prefix
    char* result = crypt("password", "$5$test$");
    ASSERT_NE(result, nullptr);
    
    // Should start with $5$
    EXPECT_EQ(result[0], '$');
    EXPECT_EQ(result[1], '5');
    EXPECT_EQ(result[2], '$');
}
